### ISSUE TITLE
Plugin, laggs, RAM

### ISSUE THREAD

**Issue by Amauryroco** [zDevelopers/UHPlugin#103] opened 2015-05-15 13:20 UTC
Hello !

I have used this plugin for many Uhc matches but I've had always laggs on my server. And this is a problem, though before changing the host, I wanted to know if it's the plugin's fault.
I explain. I don't remembered if I had laggs with @Azenet 's plugin but I do have laggs with this one. The server I'm using can handle FTB but cannot handle this.
I am hosting my server on OmgServ:
2GB of Ram (Though they told me it will change the amount of Ram the server's allowed to use automatically when needed, but I don't trust this sh*t)

I want to host many other Uhc matches, but I don't know what's the problem so I figured maybe it's the host. I found many other hosting companies with 8+ GB of Ram, and I wondered how many Ram does the plugin take with WorldBorder, etc...

Has anyone did a Uhc match with a host without laggs ? Can someone tell me what host can handle an Uhc ? Is it the plugin's fault ? Does it lagg because the server doesn't have enough RAM ?

**Comment by jonyroda97** [comment] 2015-05-15 13:43
Do you pre generate the chunks with worldborder?

**Comment by Amauryroco** [comment] 2015-05-15 13:51
Before uploading the map, I generate it by exploring it (fly mod creative) to generate all chunks. Then I upload it to the server and I do /wb fill to be sure it's all generated. After that I just stop the server and 1-2 days after I configure the config.yml file and start the server and 30min later I start the game. I still do /wb fill just before starting again, so that the worldborder is active. And I do a /uh start slow

**Comment by jonyroda97** [comment] 2015-05-15 13:57
I've helped a gaming community to prepare and play an UHC and on the 1st try I forgot to pre generate the chunks and the all server, because there were so many players being teleported (I used the fast start), lagged, a lot, and the players logged out because of it.

**Comment by jonyroda97** [comment] 2015-05-15 13:58
normally how many players do you have on your server playing?

**Comment by Amauryroco** [comment] 2015-05-15 14:07
In teams of 2, 30 players so 15 spawn points in a world 1200 x 1200. But I also want to do Solo matches for 20-25 players or more...

**Comment by Amauryroco** [comment] 2015-05-15 17:13
Any suggestions ?

**Comment by jonyroda97** [comment] 2015-05-15 18:04
Don't know where do the lag come from but I had no lag at all when I helped that community so... I think that it isn't a problem of the plugin.

You're French right, and the players too I presume. Where is the server located?

**Comment by Azenet** [comment] 2015-05-15 18:13
@Amauryroco You should profile the plugin. Enable plugin-profiling in bukkit.yml, type /timings on at the start of the game, type /timings merged after a little while, then send the timings.txt here. More details are available on Spigot, if you're using Craftbukkit.

**Comment by Amauryroco** [comment] 2015-05-15 20:22
The server is located in France @jonyroda97 . I have 4 ms according to Minecraft
I'll try to do that @Azenet . Do I need the players to do that ? The timings.txt will be sent A.S.A.P.
I can assume it's the server's fault then ;_; I checked, FTB uses 1,6 Go of RAM, so I guess it was pretty close to lagg...

**Comment by Relicum** [comment] 2015-08-08 01:57
I kow this is a little late but i can clearly see the problem. If you run wb fill just before you start the game this is going to be the exact cause of the lag. I presume you are running it with force set to true to force the chunks to repopulate. This is completely pointless along with the flying around before you run the wb fill the first time. reason being is unless you have altered the terrain running wb fill a 2nd time will do nothing. I see you login you are running to load the chunks the spawns are located in. This is easy to do from a coding point of view. I speak from experience as I am the dev for UHCZone and we use this plugin (very modified version) as a base for all are different game UHC game modes. I can run a 24 player speed uhc whiich is far more intensive than default on 1GB of ram no problem. I can confirm this plugin is more than capable of running 150+ player UHC's.

**Closed** 2015-12-19 00:06 UTC
Labels: Support Request
