### ISSUE TITLE
Chest-GUI full team click error

### ISSUE THREAD

**Issue by TheIronMinerLv** [zDevelopers/UHPlugin#142] opened 2016-12-19 14:26 UTC
*The following template is required if you report a bug. For a suggestion, you can clear this, but don't forget to open one issue per suggestion!*

#### Environment

* **Minecraft version**: 1.11
* **Plateform used**: Paperspigot, tried with spigot too.
* **Bukkit or Spigot version**: 1.11
* **Plugin version**: Newest from jenkins (1.3, 15th December build)
* **Plugin build number**: (Check out the CONTRIBUTING file linked above the form to see where this number is) 389

#### Problem description

When someone clicks on a full team, this error shows in console:
http://pastebin.com/JVciCcSZ

#### Steps to reproduce

Just click on a full team in Chest-GUI.

**Comment by AmauryCarrade** [comment] 2016-12-19 15:20
Duplicate of #136, but thanks for bringing that up, I'll fix that before 1.4.

**Closed by AmauryCarrade** 2016-12-19 15:20 UTC
